# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: GitHub Pages deploy -- CI / CD for Next.JS

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Set up Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT

      - name: Cache node modules
        uses: actions/cache@v3
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build && npm run export && touch ./out/.nojekyll
              
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: /
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            #error en la ubicación del built
      #- name: Next to Github Pages
       # uses: ricardobiundo/NextPagesAction@1.0.2
       # with:
       #   username: 'karen-valenzuela-landero'
       #   reponame: 'admin-dashboard-react'
       #   token: ${{ secrets.GITHUB_TOKEN }} 
    
      #- name: Deploy to GitHub Pages
       # uses: JamesIves/github-pages-deploy-action@v4.5.0
       # with:
        #  folder: build # The folder the action will deploy to